work_dir: ./work_dir/nfl5
#weights: ./weights/regnety_120-721ba79a.pth

# feeder
feeder: feeder.nfl.Feeder
train_feeder_args:
  debug: 0
  df_path: './train_filtered.pkl'
  fc_path: './train_featurecol.pkl'
  vf_path: './train_video2frames.pkl'
  vh_path: './train_video2helmets.pkl'
  fm_path: './frames'
  mode: 'train'

optimizer: 'Adam'

test_feeder_args:
  debug: 0
  df_path: './test_filtered.pkl'
  fc_path: './featurecol.pkl'
  vf_path: './video2frames.pkl'
  vh_path: './video2helmets.pkl'
  fm_path: './frames'
  mode: 'test'

# model
model: model.baseline.Model
model_args:
  bm: mobilenetv3_large_100

#training
device: [0,1]
batch_size: 8
test_batch_size: 100

#optim
base_lr: 0.001
step: [150, 225]
num_epoch: 20
lr_decay_rate: 1
warm_up_epoch: 1
save_epoch: 0
weight_decay: 0.000001
momentum: 0
seed: 42
grad_norm: True
clip: 1000